### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by chentsulin** [chentsulin/electron-react-boilerplate#37]
- [x] eslint-config-airbnb
- [x] bump dependencies
- ~~rewrite package.js using promise~~
- ~~upgrade to electron-packager v5.x and `--all`~~ (synchronous, more slow)
- [x] tests with babel-register (#29)
- [x] simplify webpack configs
- [x] use electron-prebuilt version for packaging (#33)
- ~~yeoman generator~~ (clone from github instead)
- [x] babel-plugin-react-transform (#44)
- [x] react, react-dom v0.14
- [x] react-router v1.0 (waiting for release)
- [x] redux?
- [x] E2E test case
- [x] 0.35.x change
- [x] use es2015 syntax which enabled in node 4
- [x] remove chrome devtools in production
- [ ] auto updater - see https://github.com/atom/electron/issues/1479
- [x] babel 6 (wait https://github.com/gaearon/babel-plugin-react-transform/pull/50)
- [x] react-router 2
- [x] Advanced electron-packager settings
- [x] babel-react-optimize (#238)
- [x] electron-builder

Wait Upstream
- [x] support react devtools when atom/electron#915 fixed
- [x] change target when https://github.com/webpack/webpack/pull/1467 ship in new release (now only in webpack 2.x).
## Investigate
- [ ] webpack2
- [ ] electron-updater
- [ ] electron-compile
- ~~electron-dl~~

**Comment by TheSisb** [comment]
Redux.

**Comment by yinhm** [comment]
redux +1

**Comment by jhen0409** [comment]
Add E2E test cases? :D

Refer [using-selenium-and-webdriver.md](https://github.com/atom/electron/blob/master/docs/tutorial/using-selenium-and-webdriver.md), and this [commit](https://github.com/atom/electron/commit/c7dc901607b2320cdbe2cb6119e6d84a5765a606) (released by 0.33.7), so we can start main process by chromedriver.

These work well in my private projects.

**Comment by chentsulin** [comment]
@jhen0409 definitely have interest in this. I will add some redux stuffs after React 0.14-compatible react-redux and react-devtools released. Are you willing to make a PR at that moment?

**Comment by jhen0409** [comment]
@chentsulin yes, I will. :)

**Comment by gbmhunter** [comment]
redux +1

**Comment by joernroeder** [comment]
redux +1

**Comment by geminiyellow** [comment]
redux is done, but babel 6 not.

**Comment by dmr** [comment]
babel is done by now :)

**Comment by amilajack** [comment]
@chentsulin can we release `0.11.0`?

**Comment by chentsulin** [comment]
Sure. And we should document significant changes between 0.10 and 0.11 in CHANGELOG.

**Comment by amilajack** [comment]
Closing this in favor of https://github.com/chentsulin/electron-react-boilerplate/issues/504
